# Generated by Django 4.1.3 on 2022-12-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
