# Generated by Django 4.1.3 on 2023-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
